name: TfL image processing UI
language: nodejs
variables:
  - name: processed
    inputType: InputTopic
    description: The topic to read from
    defaultValue: image-processed-merged
    required: true
  - name: bearerToken
    inputType: Secret
    description: ''
    defaultValue: PAT
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
